<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\EventNest.Shared\EventNest.Shared.Infrastructure\EventNest.Shared.Infrastructure.csproj" />
    <ProjectReference Include="..\..\EventNest.Shared\EventNest.Shared.Domain\EventNest.Shared.Domain.csproj" />
    <ProjectReference Include="..\..\EventNest.Shared\EventNest.Shared.Application\EventNest.Shared.Application.csproj" />
    <ProjectReference Include="..\EventNest.AuthService.Application\EventNest.AuthService.Application.csproj" />
    <ProjectReference Include="..\EventNest.AuthService.Infrastructure\EventNest.AuthService.Infrastructure.csproj" />
    <ProjectReference Include="..\EventNest.AuthService.Domain\EventNest.AuthService.Domain.csproj" />
  </ItemGroup>

</Project>
