<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventNest.AuthService.Application\EventNest.AuthService.Application.csproj" />
    <ProjectReference Include="..\EventNest.AuthService.Infrastructure\EventNest.AuthService.Infrastructure.csproj" />
    <ProjectReference Include="..\EventNest.AuthService.Domain\EventNest.AuthService.Domain.csproj" />
  </ItemGroup>

</Project>
